var bookDict = {
'Obadiah': '/study/scriptures/ot/obad/',
'Genesis': '/study/scriptures/ot/gen/',
'Exodus': '/study/scriptures/ot/ex/',
'Leviticus': '/study/scriptures/ot/lev/',
'Numbers': '/study/scriptures/ot/num/',
'Deuteronomy': '/study/scriptures/ot/deut/',
'Joshua': '/study/scriptures/ot/josh/',
'Judges': '/study/scriptures/ot/judg/',
'Ruth': '/study/scriptures/ot/ruth/',
'1 Samuel': '/study/scriptures/ot/1-sam/',
'2 Samuel': '/study/scriptures/ot/2-sam/',
'1 Kings': '/study/scriptures/ot/1-kgs/',
'2 Kings': '/study/scriptures/ot/2-kgs/',
'1 Chronicles': '/study/scriptures/ot/1-chr/',
'2 Chronicles': '/study/scriptures/ot/2-chr/',
'Ezra': '/study/scriptures/ot/ezra/',
'Nehemiah': '/study/scriptures/ot/neh/',
'Esther': '/study/scriptures/ot/esth/',
'Job': '/study/scriptures/ot/job/',
'Psalms': '/study/scriptures/ot/ps/',
'Proverbs': '/study/scriptures/ot/prov/',
'Ecclesiastes': '/study/scriptures/ot/eccl/',
'Song of Solomon': '/study/scriptures/ot/song/',
'Isaiah': '/study/scriptures/ot/isa/',
'Jeremiah': '/study/scriptures/ot/jer/',
'Lamentations': '/study/scriptures/ot/lam/',
'Ezekiel': '/study/scriptures/ot/ezek/',
'Daniel': '/study/scriptures/ot/dan/',
'Hosea': '/study/scriptures/ot/hosea/',
'Joel': '/study/scriptures/ot/joel/',
'Amos': '/study/scriptures/ot/amos/',
'Jonah': '/study/scriptures/ot/jonah/',
'Micah': '/study/scriptures/ot/micah/',
'Nahum': '/study/scriptures/ot/nahum/',
'Habakkuk': '/study/scriptures/ot/hab/',
'Zephaniah': '/study/scriptures/ot/zeph/',
'Haggai': '/study/scriptures/ot/hag/',
'Zechariah': '/study/scriptures/ot/zech/',
'Malachi': '/study/scriptures/ot/mal/',
'Philemon': '/study/scriptures/nt/philem/',
'2 John': '/study/scriptures/nt/2-jn/',
'3 John': '/study/scriptures/nt/3-jn/',
'Jude': '/study/scriptures/nt/jude/',
'Matthew': '/study/scriptures/nt/matt/',
'Mark': '/study/scriptures/nt/mark/',
'Luke': '/study/scriptures/nt/luke/',
'John': '/study/scriptures/nt/john/',
'Acts': '/study/scriptures/nt/acts/',
'Romans': '/study/scriptures/nt/rom/',
'1 Corinthians': '/study/scriptures/nt/1-cor/',
'2 Corinthians': '/study/scriptures/nt/2-cor/',
'Galatians': '/study/scriptures/nt/gal/',
'Ephesians': '/study/scriptures/nt/eph/',
'Philippians': '/study/scriptures/nt/philip/',
'Colossians': '/study/scriptures/nt/col/',
'1 Thessalonians': '/study/scriptures/nt/1-thes/',
'2 Thessalonians': '/study/scriptures/nt/2-thes/',
'1 Timothy': '/study/scriptures/nt/1-tim/',
'2 Timothy': '/study/scriptures/nt/2-tim/',
'Titus': '/study/scriptures/nt/titus/',
'Hebrews': '/study/scriptures/nt/heb/',
'James': '/study/scriptures/nt/james/',
'1 Peter': '/study/scriptures/nt/1-pet/',
'2 Peter': '/study/scriptures/nt/2-pet/',
'1 John': '/study/scriptures/nt/1-jn/',
'Revelation': '/study/scriptures/nt/rev/',
'Enos': '/study/scriptures/bofm/enos/',
'Jarom': '/study/scriptures/bofm/jarom/',
'Omni': '/study/scriptures/bofm/omni/',
'Words of Mormon': '/study/scriptures/bofm/w-of-m/',
'4 Nephi': '/study/scriptures/bofm/4-ne/',
'Testimony of Three Witnesses': '/study/scriptures/bofm/three?lang=eng',
'Testimony of Eight Witnesses': '/study/scriptures/bofm/eight?lang=eng',
'1 Nephi': '/study/scriptures/bofm/1-ne/',
'2 Nephi': '/study/scriptures/bofm/2-ne/',
'Jacob': '/study/scriptures/bofm/jacob/',
'Mosiah': '/study/scriptures/bofm/mosiah/',
'Alma': '/study/scriptures/bofm/alma/',
'Helaman': '/study/scriptures/bofm/hel/',
'3 Nephi': '/study/scriptures/bofm/3-ne/',
'Mormon': '/study/scriptures/bofm/morm/',
'Ether': '/study/scriptures/bofm/ether/',
'Moroni': '/study/scriptures/bofm/moro/',
'D&amp;C': '/study/scriptures/dc-testament/dc/',
'Official Declaration 1': '/study/scriptures/dc-testament/od/',
'Official Declaration 2': '/study/scriptures/dc-testament/od/2?lang=eng',
'JSM': '/study/scriptures/pgp/js-m/',
'JSH': '/study/scriptures/pgp/js-h/',
'Articles of Faith': '/study/scriptures/pgp/a-of-f/',
'Moses': '/study/scriptures/pgp/moses/',
'Abraham': '/study/scriptures/pgp/abr/'}










